-- Arcade Hub: credits + scores tables (server-awarded credits only)

-- 1) Credits table (public.users)
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  credits integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own credits" ON public.users;
CREATE POLICY "Users can view their own credits"
  ON public.users
  FOR SELECT
  TO authenticated
  USING (id = auth.uid());

-- 2) Scores table (leaderboards)
CREATE TABLE IF NOT EXISTS public.scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_name text NOT NULL CHECK (game_name IN ('flappy', 'snake', 'stack')),
  score integer NOT NULL CHECK (score >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read leaderboards" ON public.scores;
CREATE POLICY "Authenticated can read leaderboards"
  ON public.scores
  FOR SELECT
  TO authenticated
  USING (true);

-- No insert/update policies on purpose (edge function uses service role).

CREATE INDEX IF NOT EXISTS scores_game_score_idx ON public.scores (game_name, score DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS scores_user_game_created_idx ON public.scores (user_id, game_name, created_at DESC);

-- 3) Atomic credit increment helper (service role only)
CREATE OR REPLACE FUNCTION public.arcade_increment_credits(p_user_id uuid, p_delta integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_credits integer;
BEGIN
  INSERT INTO public.users (id, credits)
  VALUES (p_user_id, 0)
  ON CONFLICT (id) DO NOTHING;

  UPDATE public.users
  SET credits = credits + p_delta,
      updated_at = now()
  WHERE id = p_user_id
  RETURNING credits INTO new_credits;

  RETURN COALESCE(new_credits, 0);
END;
$$;

REVOKE ALL ON FUNCTION public.arcade_increment_credits(uuid, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.arcade_increment_credits(uuid, integer) TO service_role;

-- 4) Ensure new signups get a credits row (extend existing handle_new_user)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, email, full_name, auth_provider)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.raw_app_meta_data->>'provider', 'email')
  )
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.users (id, credits)
  VALUES (NEW.id, 0)
  ON CONFLICT (id) DO NOTHING;

  IF EXISTS (SELECT 1 FROM public.initial_admins WHERE email = NEW.email) THEN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'admin')
    ON CONFLICT (user_id) DO UPDATE SET role = 'admin';
  ELSE
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'role', 'client'))
    ON CONFLICT (user_id) DO UPDATE SET role = EXCLUDED.role;
  END IF;

  RETURN NEW;
END;
$$;

